# Generated by Django 4.0.6 on 2022-07-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='Author 1', max_length=255),
            preserve_default=False,
        ),
    ]
