# Generated by Django 4.0.6 on 2022-07-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_book', '0013_genres_comment_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
