# Generated by Django 4.0.6 on 2022-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_book', '0016_remove_book_genres_genres_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Western', 'Western'), ('Bildungsroman', 'Bildungsroman'), ('Speculative Fiction', 'Speculative Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Dystopian', 'Dystopian'), ('Magical Realism', 'Magical Realism'), ('Realist Literature', 'Realist Literature'), ('Literary Fiction', 'Literary Fiction')], null=True),
        ),
    ]
