# Generated by Django 4.0.6 on 2022-07-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_book', '0018_alter_genres_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='read_book.genres'),
        ),
    ]
