# Generated by Django 4.0.6 on 2022-07-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_book', '0021_alter_genres_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='read_book.genres'),
        ),
    ]
