# Generated by Django 4.0.6 on 2022-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_book', '0022_alter_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre',
            field=models.CharField(blank=True, choices=[('mystery', 'Mystery'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('historical', 'Historical'), ('romance', 'Romance'), ('western', 'Western'), ('bildungsroman', 'Bildungsroman'), ('speculative fiction', 'Speculative Fiction'), ('science fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('dystopian', 'Dystopian'), ('magical realism', 'Magical Realism'), ('realist literature', 'Realist Literature'), ('literary fiction', 'Literary Fiction')], max_length=50, unique=True),
        ),
    ]
