# Generated by Django 4.0.6 on 2022-07-31 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('read_book', '0023_alter_genres_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, verbose_name='Comment')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='read_book.book', verbose_name='books')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
