# Generated by Django 4.0.6 on 2022-08-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_book', '0027_alter_like_user_alter_rating_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
